### ISSUE TITLE
Released versions is on 1.3.3, setup.py here states 1.3.2

### ISSUE THREAD

**Issue by jensens** [collective/collective.blogging#4]
seems like there is something missing

**Comment by jensens** [comment]
@naro @lzdych I would like to release this package with the latest fixes, so we can update an old Plone 4.3 site, may one of you give me access on PyPI so I can do so? (user: jensens). Thanks!

**Comment by naro** [comment]
Hi Jens,

I have just added you.

Cheers,
Radim

**Comment by jensens** [comment]
Thanks! I released a cleaned up 1.4.0.
